import type { Metadata, Viewport } from "next";
import "./globals.css";
import { RuntimeBoundary } from "@/components/runtime-boundary";

export const metadata: Metadata = {
  title: "FullTime — encrypted peer-to-peer match rooms",
  description:
    "Create an invite-only Pear room for a signed fixture, then chat, poll, reply, and react directly with your group.",
  applicationName: "FullTime",
  manifest: "/manifest.webmanifest",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "FullTime" },
  // Favicon here; the iOS apple-touch-icon PNG is generated by app/apple-icon.tsx.
  icons: { icon: "/icon.svg" },
};

export const viewport: Viewport = {
  themeColor: "#f6f3f1",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">
        <RuntimeBoundary>{children}</RuntimeBoundary>
      </body>
    </html>
  );
}
