import type { Metadata, Viewport } from "next";
import "./globals.css";
import { RuntimeBoundary } from "@/components/runtime-boundary";
import { FullTimeWalletProvider } from "@/lib/slip/privy-provider";

export const metadata: Metadata = {
  title: "FullTime — encrypted peer-to-peer match rooms",
  description:
    "Create an invite-only Pear room for a signed fixture, then chat, poll, reply, and react directly with your group.",
  applicationName: "FullTime",
  manifest: "/manifest.webmanifest",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "FullTime" },
  // Favicon here; the iOS apple-touch-icon PNG is generated by app/apple-icon.tsx.
  icons: { icon: "/icon.svg" },
};

export const viewport: Viewport = {
  themeColor: "#f6f3f1",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const configuredNetwork = process.env.NEXT_PUBLIC_SLIP_NETWORK;
  const network = configuredNetwork === "devnet" || configuredNetwork === "mainnet-beta" ? configuredNetwork : "localnet";
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">
        <FullTimeWalletProvider configuration={{
          appId: process.env.PRIVY_APP_ID?.trim() || process.env.NEXT_PUBLIC_PRIVY_APP_ID?.trim() || null,
          clientId: process.env.PRIVY_CLIENT_ID?.trim() || process.env.NEXT_PUBLIC_PRIVY_CLIENT_ID?.trim() || null,
          network,
          rpcUrl: process.env.NEXT_PUBLIC_SLIP_RPC_URL?.trim() || null,
          websocketUrl: process.env.NEXT_PUBLIC_SLIP_WEBSOCKET_URL?.trim() || null,
        }}>
          <RuntimeBoundary>{children}</RuntimeBoundary>
        </FullTimeWalletProvider>
      </body>
    </html>
  );
}
